### ISSUE TITLE
Solenoid connection with pi

### ISSUE THREAD

**Issue by rjtshrm** [google-coral/project-teachable-sorter#31]
Did you directly connect solenoid puh/pull with the pi or use some resistors or diodes.

**Comment by hjonnala** [comment]
We used a simple transistor circuit to control the solenoid, but you could also connect it a number of ways.
This guide describes the exact method we used, with the tip120 transistor + a diode + resistor: 
https://adam-meyer.com/arduino/TIP120

This guide using a relay would also work very well, and doesn't require a diode or resistor:
 https://core-electronics.com.au/guides/solenoid-control-with-raspberry-pi-relay/
