### ISSUE TITLE
Solenoid linear motion to rotation

### ISSUE THREAD

**Issue by rjtshrm** [google-coral/project-teachable-sorter#32]
Hi @hjonnala  , Just needed to know how did you transform the solenoid linear motion to sorter rotation. Did you use some kind of gears to the conversion form linear to rotation because as far I know solenoid mover in one direction (front or back). Another option is to use Stepper motor which is kind of expensive.

**Comment by hjonnala** [comment]
Hello..The mechanism we used is actually provided as 3D files here: https://github.com/google-coral/project-teachable-sorter/tree/master/3D_files/tippy

These are designed to be FDM printed, and turn the solenoids motion into the tippy thing that's seen in the video. The solenoid sits in the part called `solenoidholder.stl`, which should be adhered to the tab on` body.stl`. Then the solenoid's output shaft can be connected to the part called `track.stl` with a small, rigid linkage, we used a paperclip.

**Comment by rjtshrm** [comment]
Do you have a pic of back surface because it would be hard to understand how does it rotate the track in either direction.

**Comment by hjonnala** [comment]
Here is the image and small cam looking part that used to create the motion needed: https://github.com/hjonnala/snippets/blob/main/cam.stl

![IMG_5366](https://user-images.githubusercontent.com/86132058/163471929-ce125b08-5a38-4c5d-b080-516782fd7e4d.jpg)
