### ISSUE TITLE
Setting up a NeoPixel Ring

### ISSUE THREAD

**Issue by rjtshrm** [google-coral/project-teachable-sorter#33]
Hi, I have setup the sorter by myself but for the final finishing I am trying to setup the NeoPixel ring. Just wanted to ask did you directly used the NeoPixel with the Pi or used it with the external power source as the LED's a trying heavy load of current. Also, did you use the GPIO 18 or any (PWM pin) as well for the setup.

**Comment by hjonnala** [comment]
Hi,
The NeoPixels must use an external 5v power source, as they draw too much power to for the Pi. Make sure to use a common ground between the power supply for the neopixels and the power supply for the Pi. This guide describes how the wiring should be set up: https://learn.adafruit.com/neopixels-on-raspberry-pi/raspberry-pi-wiring#using-external-power-source-without-level-shifting-3005993-11

We do use pin d18 as described in that guide as well under the 'Python usage' section. NeoPixels must be connected to pins D10, D12, D18 or D21 to work.
