### ISSUE TITLE
Two cameras installation required 

### ISSUE THREAD

**Issue by raffaeletavolieri** [google-coral/project-teachable-sorter#37]
### Description

Hi, I have looked carefully at your project, and I was extremely excited about it.  I wanted to ask you if I wanted to insert two cameras, for the sole fact that, in the visualization at this moment, I only see face A, and not the rear face B, I would like to separate some seeds, and I would like to discard some spots on the seeds.  so I thought of inserting a second camera at 180 ° opposite to the primary, to view side b.  the problem is to understand whether to insert a double equipment, or can it manage everything with just one Coral?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

_No response_

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
I think, There are two options here
Option A, probably easier to setup: Stitch the two images together before feeding them in to teachable machine or classification using openCV. This way you only need one model, but it might lose some fidelity as each image is only half the resolution.

Option B, might yield more accurate results: Create a second instance of the classifier on the coral for the second camera, and train a second model. Use one coral with the [Co-compilation](https://coral.ai/docs/edgetpu/compiler/#co-compiling-multiple-models) if both models can be fit on single SRAM(8MB) or use 2 coral's one for each model. This is untested though and I'm not sure if it will work.

**Comment by raffaeletavolieri** [comment]
> Penso che ci siano due opzioni qui Opzione A, probabilmente più facile da configurare: unisci le due immagini prima di inserirle nella macchina insegnabile o nella classificazione usando openCV. In questo modo è necessario un solo modello, ma potrebbe perdere un po' di fedeltà poiché ogni immagine ha solo la metà della risoluzione.
> 
> L'opzione B potrebbe produrre risultati più accurati: crea una seconda istanza del classificatore sul corallo per la seconda fotocamera e addestra un secondo modello. Usa un corallo con la [Co-compilation](https://coral.ai/docs/edgetpu/compiler/#co-compiling-multiple-models) se entrambi i modelli possono essere inseriti su una singola SRAM (8 MB) o usa 2 coralli uno per ogni modello. Questo non è testato e non sono sicuro che funzionerà.

Thanks hjonnala, the problem is that I have to drop a seed, but I want to see the front and the back as it falls, I have the feeling that the two options are slow to choose if it is to be discarded k first quality.  And if in the fall I applied two opposite cameras at 180 ° but staggered one after the other, I would have to have double the equipment and decide if: - face A is good go to the second camera face B is stained then I reject and so on ... I wanted to save on electronic components, but I think that cooperation would make me too slow.

**Comment by raffaeletavolieri** [comment]
I'll have to spend a few euros to try
