### ISSUE TITLE
Exception: Arducam Support Coming

### ISSUE THREAD

**Issue by pachinco** [google-coral/project-teachable-sorter#7]
Looks like a cool project and bought everything to get started, just to find out that my Arducam isn't supported, although it says so in the tutorial description.
All I get is...

Traceback (most recent call last):
  File "sorter.py", line 165, in <module>
    raise Exception("Arducam Support Coming")
Exception: Arducam Support Coming

**Comment by hjonnala** [comment]
Unfortunately, due to the other priorities this feature request is not possible in the near future.
